---
- name: Copy resolver configuration
  ansible.builtin.copy:
    src: files/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
- name: Change Vagrant default NAT network (disable resolver configuration)
  ansible.builtin.copy:
    src: files/ifcfg-eth0
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: '0644'
- name: Disable NetworkManager to not change resolver configuration
  ansible.builtin.systemd:
    name: NetworkManager.service
    state: stopped
    enabled: 'no'
