---
- name: Configures master server
  hosts: master
  become: true
  gather_facts: 'no'
  vars:
    rpuser_ldif: /root/rpuser.ldif
    syncprov_overlay: /root/syncprov_overlay.ldif
    syncprov_config: /root/syncprov_config.ldif
    migrate_bin: /usr/local/sbin/posix2ldap
    temporary_ldif: /tmp/users.ldif
    users:
      - login: marcos
        fullname: Marcos Pitanga
      - login: alves
        fullname: Alves Silva
      - login: arthur
        fullname: Arthur Moura
      - login: nathalia
        fullname: Nathalia Lopes
      - login: pinguim
        fullname: Aptenodytes Forsteri
  tasks:
    - name: Migrate local from POSIX database to OpenLDAP
      ansible.builtin.include_tasks:
        file: tasks/users_migration.yml

    - name: 'Check syncprov availability (idempotence)'
      ansible.builtin.command: ldapsearch -L -Q -Y EXTERNAL -H ldapi:/// -b cn=config '(&(objectClass=olcModuleList)(olcModuleLoad=syncprov.la))'  # yamllint disable-line rule:line-length
      register: syncprov_check
    - name: ldapsearch result
      ansible.builtin.debug:
        msg: 'Last line of output is >{{ syncprov_check.stdout_lines[-1] }}<'
    - block:
        - name: Copying the syncprov overlay configuration
          ansible.builtin.copy:
            src: files/syncprov_overlay.ldif
            dest: '{{ syncprov_overlay }}'
            owner: root
            group: root
            mode: '0400'
        - name: Loading syncprov overlay configuration
          ansible.builtin.command: 'ldapadd -Y EXTERNAL -H ldapi:/// -f {{ syncprov_overlay }}'  # yamllint disable-line rule:line-length
      when: 'syncprov_check.stdout_lines[-1] == "# numResponses: 1"'

    - name: 'Check syncprov configuration availability (idempotence)'
      ansible.builtin.command: ldapsearch -L -Q -Y EXTERNAL -H ldapi:/// -b cn=config '(&(objectClass=olcSyncProvConfig)(objectClass=olcOverlayConfig))'  # yamllint disable-line rule:line-length
      register: syncprov_cfg_check
    - name: ldapsearch result
      ansible.builtin.debug:
        msg: 'Last line of output is >{{ syncprov_check.stdout_lines[-1] }}<'
    - block:
        - name: Copying the Sync Provider to slapd configuration
          ansible.builtin.copy:
            src: files/syncprov_config.ldif
            dest: '{{ syncprov_config }}'
            owner: root
            group: root
            mode: '0400'
        - name: Loading the Sync Provider to slapd configuration
          ansible.builtin.command: 'ldapadd -Y EXTERNAL -H ldapi:/// -f {{ syncprov_config }}'  # yamllint disable-line rule:line-length
      when: 'syncprov_cfg_check.stdout_lines[-1] == "# numResponses: 1"'

    - name: 'Testing if replication user configuration is already in place (idempotence)'  # yamllint disable-line rule:line-length
      ansible.builtin.command: ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:/// -b uid={{ replication_user }},{{ base_dn }} description  # yamllint disable-line rule:line-length
      ignore_errors: 'yes'
      register: rpuser_check
    - block:
        - name: Generate the hashed password for OpenLDAP replication user
          ansible.builtin.command: 'slappasswd -s {{ sync_password }}'
          register: rpuser_password
        - name: Create a LDIF file with replication user configuration
          ansible.builtin.template:
            src: templates/rpuser.ldif
            dest: '{{ rpuser_ldif }}'
            owner: root
            group: root
            mode: '0400'
        - name: Load LDIF into OpenLDAP
          ansible.builtin.command: 'ldapadd -x -w {{ admin_pass }} -D {{ admin_dn }} -f {{ rpuser_ldif }}'  # yamllint disable-line rule:line-length
      when: rpuser_check.rc == 32  # exit code for "no such object" error
