---
- name: Configures master server
  hosts: master
  become: true
  gather_facts: 'no'
  # vars:
  #   openssl_private_key: /etc/openldap/certs/priv.pem
  #   openssl_certificate: /etc/openldap/certs/cert.pem
  #   # TODO: read the password from an environment variable
  #   admin_pass: '123456'
  #   users: '/root/users.ldif'
  #   seed_data: '/root/seed_data.ldif'
  #   bootstrap_data: '/root/db_bootstrap.ldif'
  #   migrate_bin: '/usr/local/sbin/migrate-passwd'
  #   log_dir: /var/log/openldap
  #   ldap_audit_log: '{{ log_dir }}/audit.log'
  #   ldap_log: /var/log/openldap.log
  tasks:
    - name: Manage local user group
      ansible.builtin.group:
        name: it
        state: present
    - name: Manage Linux local users
      ansible.builtin.user:
        name: '{{ item["login"] }}'
        comment: '{{ item["fullname"] }},571,+551155422748,+551155422748'
        append: 'yes'
        create_home: 'yes'
        shell: /bin/bash
        state: present
        groups:
          - it
        password: '{{ item["password"] }}'
        password_expire_max: 365
        password_expire_min: 15
      loop:  # TODO: DRY for password
        - {"login": "marcos", "fullname": "Marcos Pitanga", "password": "$5$VACmpTmOAHpIVLqZ$HNj.0nxssyymqCO1ALZ4I6bFjDEOKGNmmK8ByaA9q10"}  # yamllint disable-line rule:line-length
        - {"login": "alves", "fullname": "Alves Silva", "password": "$5$VACmpTmOAHpIVLqZ$HNj.0nxssyymqCO1ALZ4I6bFjDEOKGNmmK8ByaA9q10"}  # yamllint disable-line rule:line-length
        - {"login": "arthur", "fullname": "Arthur Moura", "password": "$5$VACmpTmOAHpIVLqZ$HNj.0nxssyymqCO1ALZ4I6bFjDEOKGNmmK8ByaA9q10"}  # yamllint disable-line rule:line-length
        - {"login": "nathalia", "fullname": "Nathalia Lopes", "password": "$5$VACmpTmOAHpIVLqZ$HNj.0nxssyymqCO1ALZ4I6bFjDEOKGNmmK8ByaA9q10"}  # yamllint disable-line rule:line-length
        - {"login": "pinguim", "fullname": "Aptenodytes Forsteri", "password": "$5$VACmpTmOAHpIVLqZ$HNj.0nxssyymqCO1ALZ4I6bFjDEOKGNmmK8ByaA9q10"}  # yamllint disable-line rule:line-length
