---
- name: Configures master server
  hosts: all
  become: true
  gather_facts: 'no'
  vars:
    openssl_private_key: /etc/openldap/certs/priv.pem
    openssl_certificate: /etc/openldap/certs/cert.pem
  tasks:
    - name: Copy resolver configuration
      ansible.builtin.copy:
        src: files/resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'
    - name: Disable NetworkManager to not change resolver configuration
      ansible.builtin.systemd:
        name: NetworkManager.service
        state: stopped
        enabled: 'no'
    - name: Install packages
      yum:
        name:
          - openldap
          - openldap-clients
          - openldap-servers
          - migrationtools
          - python36-cryptography  # for Ansible community.crypto
        state: present
        update_cache: 'yes'
    - name: Generate the hashed password for OpenLDAP manager
      # TODO: read the password from an environment variable
      ansible.builtin.command: 'slappasswd -s 123456 -n'
      register: manager_password
    - name: Create a bootstrap LDIF file with OpenLDAP manager password
      ansible.builtin.template:
        src: templates/db_bootstrap.ldif
        dest: /root/db_bootstrap.ldif
        owner: root
        group: root
        mode: '0400'
    - name: 'Create private key (RSA, 4096 bits)'
      community.crypto.openssl_privatekey:
        path: '{{ openssl_private_key }}'
    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: '{{ openssl_private_key }}'
        common_name: master.local.br
        organization_name: Foobar
        country_name: BR
        state_or_province_name: São Paulo
        locality_name: São Paulo
        email_address: glasswalk3r@yahoo.com.br
        organizational_unit_name: Training
      register: csr
    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: '{{ openssl_certificate }}'
        csr_content: '{{ csr.csr }}'
        privatekey_path: '{{ openssl_private_key }}'
        provider: selfsigned
    - name: Fixing permissions for TLS certificate
      ansible.builtin.file:
        path: '{{ openssl_certificate }}'
        owner: ldap
        group: ldap
    - name: Fixing permissions for private key
      ansible.builtin.file:
        path: '{{ openssl_private_key }}'
        owner: ldap
        group: ldap
        mode: '0600'
    - name: Database configuration
      ansible.builtin.copy:
        src: /usr/share/openldap-servers/DB_CONFIG.example
        remote_src: 'yes'
        dest: /var/lib/ldap/DB_CONFIG
        owner: ldap
        group: ldap
        mode: '0644'
    - name: Testing the database configuration
      ansible.builtin.command: slaptest -u
    - name: Enabling the slapd daemon
      ansible.builtin.systemd:
        name: slapd.service
        state: started
        enabled: 'yes'
    - name: 'Testing if required schemas are in place (idempotence)'
      ansible.builtin.command: ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b cn={1}cosine,cn=schema,cn=config cn  # yamllint disable-line rule:line-length
      ignore_errors: 'yes'
      register: schema_search
    - name: Adding required LDAP schemas
      ansible.builtin.command: 'ldapadd -Y EXTERNAL -H ldapi:/// -D cn=config -f /etc/openldap/schema/{{ item }}'  # yamllint disable-line rule:line-length
      when: schema_search.rc == 32  # exit code for "no such object" error
      loop:
        - cosine.ldif
        - nis.ldif
        - inetorgperson.ldif
        - misc.ldif

    - name: 'Testing if monitor access is already configured (idempotence)'
      ansible.builtin.command: ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b cn=config '(olcDatabase={1}monitor)' -Q  # yamllint disable-line rule:line-length
      ignore_errors: 'yes'
      register: monitor_access_check
    - block:
        - name: Monitor acess configuration
          ansible.builtin.copy:
            src: files/monitor.ldif
            dest: /root/monitor.ldif
            owner: ldap
            group: ldap
            mode: '0644'
        - name: apply LDIF
          ansible.builtin.command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /root/monitor.ldif  # yamllint disable-line rule:line-length
      # exit code for "no such object" error
      when: monitor_access_check.rc == 32

    - name: Configuring rsyslog to accept OpenLDAP logging
      ansible.builtin.copy:
        src: files/rsyslog.conf
        dest: /etc/rsyslog.d/openldap.conf
    - name: Reloading the rsyslog daemon
      ansible.builtin.systemd:
        name: rsyslog.service
        state: restarted
        enabled: 'yes'
    # - name: Add local users
    # TODO: add all local users and migrate them to OpenLDAP
