---
- name: Configures master server
  hosts: master
  become: true
  gather_facts: 'no'
  vars:
    users:
      - login: marcos
        fullname: Marcos Pitanga
      - login: alves
        fullname: Alves Silva
      - login: arthur
        fullname: Arthur Moura
      - login: nathalia
        fullname: Nathalia Lopes
      - login: pinguim
        fullname: Aptenodytes Forsteri
  tasks:
    - name: Manage local user group
      ansible.builtin.group:
        name: it
        state: present
    - name: Manage Linux local users
      ansible.builtin.user:
        name: '{{ item["login"] }}'
        comment: '{{ item["fullname"] }},571,+551155422748,+551155422748'
        append: 'yes'
        create_home: 'yes'
        shell: /bin/bash
        state: present
        groups:
          - it
        password: '{{ "abc@123" | password_hash("sha512", "mysecretsalt") }}'
        password_expire_max: 365
        password_expire_min: 15
      loop: '{{ users }}'
