---
- name: Configures master server
  hosts: all
  become: true
  gather_facts: 'no'
  vars:
    openssl_private_key: /etc/openldap/certs/priv.pem
    openssl_certificate: /etc/openldap/certs/cert.pem
    # TODO: read the password from an environment variable
    admin_pass: '123456'
    users: '/root/users.ldif'
    seed_data: '/root/seed_data.ldif'
    bootstrap_data: '/root/db_bootstrap.ldif'
    migrate_bin: '/usr/local/sbin/migrate-passwd'
  tasks:
    - name: Copy resolver configuration
      ansible.builtin.copy:
        src: ../resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'
    - name: Disable NetworkManager to not change resolver configuration
      ansible.builtin.systemd:
        name: NetworkManager.service
        state: stopped
        enabled: 'no'
    - name: Install packages
      yum:
        name:
          - openldap
          - openldap-clients
          - openldap-servers
          - migrationtools
          - python36-cryptography  # for Ansible community.crypto
        state: present
        update_cache: 'yes'

    - name: 'Create private key (RSA, 4096 bits)'
      community.crypto.openssl_privatekey:
        path: '{{ openssl_private_key }}'
    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: '{{ openssl_private_key }}'
        common_name: master.local.br
        organization_name: Foobar
        country_name: BR
        state_or_province_name: São Paulo
        locality_name: São Paulo
        email_address: glasswalk3r@yahoo.com.br
        organizational_unit_name: Training
      register: csr
    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: '{{ openssl_certificate }}'
        csr_content: '{{ csr.csr }}'
        privatekey_path: '{{ openssl_private_key }}'
        provider: selfsigned
    - name: Fixing permissions for TLS certificate
      ansible.builtin.file:
        path: '{{ openssl_certificate }}'
        owner: ldap
        group: ldap
    - name: Fixing permissions for private key
      ansible.builtin.file:
        path: '{{ openssl_private_key }}'
        owner: ldap
        group: ldap
        mode: '0600'
    - name: Database configuration
      ansible.builtin.copy:
        src: /usr/share/openldap-servers/DB_CONFIG.example
        remote_src: 'yes'
        dest: /var/lib/ldap/DB_CONFIG
        owner: ldap
        group: ldap
        mode: '0644'
    - name: Testing the database configuration
      ansible.builtin.command: slaptest -u
    - name: Enabling the slapd daemon
      ansible.builtin.systemd:
        name: slapd.service
        state: started
        enabled: 'yes'

    - name: 'Testing if required schemas are in place (idempotence)'
      ansible.builtin.command: ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b cn={1}cosine,cn=schema,cn=config cn  # yamllint disable-line rule:line-length
      ignore_errors: 'yes'
      register: schema_search
    - name: Adding required LDAP schemas
      ansible.builtin.command: 'ldapadd -Y EXTERNAL -H ldapi:/// -D cn=config -f /etc/openldap/schema/{{ item }}'  # yamllint disable-line rule:line-length
      when: schema_search.rc == 32  # exit code for "no such object" error
      loop:
        - cosine.ldif
        - nis.ldif
        - inetorgperson.ldif
        - misc.ldif

    - name: Generate the hashed password for OpenLDAP manager
      ansible.builtin.command: 'slappasswd -s {{ admin_pass }}'
      register: manager_password
    - name: Create a bootstrap LDIF file with OpenLDAP manager password
      ansible.builtin.template:
        src: templates/db_bootstrap.ldif
        dest: '{{ bootstrap_data }}'
        owner: root
        group: root
        mode: '0400'
    - name: Loading bootstrap data
      ansible.builtin.command: 'ldapadd -Y EXTERNAL -H ldapi:/// -f {{ bootstrap_data }}'  # yamllint disable-line rule:line-length

    - name: Manage local user group
      ansible.builtin.group:
        name: it
        state: present

    - name: Manage Linux local users
      ansible.builtin.user:
        name: '{{ item["login"] }}'
        comment: '{{ item["fullname"] }},571,+551155422748,+551155422748'
        append: 'yes'
        create_home: 'yes'
        shell: /bin/bash
        state: present
        groups:
          - it
        password: '{{ item["password"] }}'
        password_expire_max: 365
        password_expire_min: 15
      loop:
        - {"login": "marcos", "fullname": "Marcos Pitanga", "password": "$5$VACmpTmOAHpIVLqZ$HNj.0nxssyymqCO1ALZ4I6bFjDEOKGNmmK8ByaA9q10"}  # yamllint disable-line rule:line-length
        - {"login": "alves", "fullname": "Alves Silva", "password": "$5$VACmpTmOAHpIVLqZ$HNj.0nxssyymqCO1ALZ4I6bFjDEOKGNmmK8ByaA9q10"}  # yamllint disable-line rule:line-length
        - {"login": "arthur", "fullname": "Arthur Moura", "password": "$5$VACmpTmOAHpIVLqZ$HNj.0nxssyymqCO1ALZ4I6bFjDEOKGNmmK8ByaA9q10"}  # yamllint disable-line rule:line-length
        - {"login": "nathalia", "fullname": "Nathalia Lopes", "password": "$5$VACmpTmOAHpIVLqZ$HNj.0nxssyymqCO1ALZ4I6bFjDEOKGNmmK8ByaA9q10"}  # yamllint disable-line rule:line-length
        - {"login": "pinguim", "fullname": "Aptenodytes Forsteri", "password": "$5$VACmpTmOAHpIVLqZ$HNj.0nxssyymqCO1ALZ4I6bFjDEOKGNmmK8ByaA9q10"}  # yamllint disable-line rule:line-length

    - name: 'Testing if seed data is already in place (idempotence)'
      ansible.builtin.command: ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:/// -b dc=local,dc=br 'objectclass=organizationalUnit'  # yamllint disable-line rule:line-length
      ignore_errors: 'yes'
      register: seed_data_check

    - block:
        - name: Copy seed data LDIF
          ansible.builtin.copy:
            src: 'files/seed_data.ldif'
            dest: '{{ seed_data }}'
            mode: '0400'

        - name: Load seed data into OpenLDAP
          ansible.builtin.command: 'ldapadd -x -w {{ admin_pass }} -D cn=Manager,dc=local,dc=br -f {{ seed_data }}'  # yamllint disable-line rule:line-length

      # exit code for "no such object" error
      when: seed_data_check.rc == 32

    - name: 'Testing if users are already in place (idempotence)'
      ansible.builtin.command: ldapsearch -LLL -Q -Y EXTERNAL -H ldapi:/// -b uid=pinguim,ou=People,dc=local,dc=br  # yamllint disable-line rule:line-length
      ignore_errors: 'yes'
      register: users_check

    - block:
        - name: Setup migrate-passwd
          ansible.builtin.copy:
            src: '../migration/migrate-passwd'
            dest: '{{ migrate_bin }}'
            mode: '0550'
        - name: Exports data from /etc/passwd and /etc/shadow
          ansible.builtin.command: '{{ migrate_bin }} -base-dn dc=local,dc=br -dns-domain local.br -save-to {{ users }}'  # yamllint disable-line rule:line-length
        - name: Load users into OpenLDAP
          ansible.builtin.command: 'ldapadd -x -w {{ admin_pass }} -D cn=Manager,dc=local,dc=br -f {{ users }}'  # yamllint disable-line rule:line-length
      # exit code for "no such object" error
      when: users_check.rc == 32

    - name: 'Testing if monitor access is already configured (idempotence)'
      ansible.builtin.command: ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b cn=config '(olcDatabase={1}monitor)' -Q  # yamllint disable-line rule:line-length
      ignore_errors: 'yes'
      register: monitor_access_check
    - block:
        - name: Monitor acess configuration
          ansible.builtin.copy:
            src: files/monitor.ldif
            dest: /root/monitor.ldif
            owner: ldap
            group: ldap
            mode: '0644'
        - name: apply LDIF
          ansible.builtin.command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /root/monitor.ldif  # yamllint disable-line rule:line-length
      # exit code for "no such object" error
      when: monitor_access_check.rc == 32

    - name: Configuring rsyslog to accept OpenLDAP logging
      ansible.builtin.copy:
        src: files/rsyslog.conf
        dest: /etc/rsyslog.d/openldap.conf
    - name: Reloading the rsyslog daemon
      ansible.builtin.systemd:
        name: rsyslog.service
        state: restarted
        enabled: 'yes'
